# Literature-based reconstruction of a real bulk semiconductor

**Part III skeleton — select exactly one crystal phase/polytype before calculation**

This notebook will construct the material-specific intrinsic model using the validated three-dimensional machinery from Part II. A webpage is only a starting point: every numerical parameter needs a definition, temperature, phase, and traceable source.

## 1. Required one-page project declaration

Complete this table before implementing the model. Zinc-blende CdTe is the lowest-complexity pathway; 4H-SiC and bulk $\mathrm{Bi_2Te_3}$ require additional anisotropy and degeneracy care.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

project_declaration = pd.DataFrame([
    ("Material identity", "TODO: formula and exact phase/polytype"),
    ("Sample model", "ideal 3D bulk crystal; TODO temperature range"),
    ("Gap model", "TODO: direct/indirect and Eg(T) source"),
    ("Conduction edge", "TODO: location, multiplicity, mass model"),
    ("Valence edge", "TODO: bands, degeneracies, mass model"),
    ("Statistics", "full Fermi-Dirac plus Boltzmann comparison"),
    ("n-type model", "TODO: species, site, charge-state model"),
    ("p-type model", "TODO: species, site, charge-state model"),
    ("Exclusions", "transport, devices, surfaces unless explicitly required"),
], columns=["item", "declaration"])
project_declaration

                item                                        declaration
0  Material identity             TODO: formula and exact phase/polytype
1       Sample model      ideal 3D bulk crystal; TODO temperature range
2          Gap model             TODO: direct/indirect and Eg(T) source
3    Conduction edge           TODO: location, multiplicity, mass model
4       Valence edge              TODO: bands, degeneracies, mass model
5         Statistics         full Fermi-Dirac plus Boltzmann comparison
6       n-type model            TODO: species, site, charge-state model
7       p-type model            TODO: species, site, charge-state model
8         Exclusions  transport, devices, surfaces unless explicitly...

## 2. Source plan and provenance

Minimum evidence:

1. one curated database or handbook;
2. two journal articles, including at least one primary research article;
3. one published band diagram or numerical band-data source.

Record DOI/URL, accessed date where appropriate, and exactly which definition was taken from each source.

In [2]:
provenance = pd.DataFrame([
    ("Band gap", "Eg", np.nan, "eV", "TODO", "TODO", "direct/indirect", "TODO"),
    ("Electron mass", "Mc or mc,d", np.nan, "m0", "TODO", "TODO", "curvature/DOS", "TODO"),
    ("Hole mass", "Mv or mv,d", np.nan, "m0", "TODO", "TODO", "HH/LH/DOS", "TODO"),
    ("Valley degeneracy", "gv", np.nan, "1", "TODO", "TODO", "included in mass?", "TODO"),
    ("Conduction effective DOS", "Nc", np.nan, "cm^-3", "TODO", "TODO", "measured/derived", "TODO"),
    ("Valence effective DOS", "Nv", np.nan, "cm^-3", "TODO", "TODO", "measured/derived", "TODO"),
    ("Intrinsic concentration", "ni", np.nan, "cm^-3", "TODO", "TODO", "method", "TODO"),
], columns=["quantity", "symbol", "value/equation", "unit", "temperature",
            "phase/polytype", "definition", "source"])
provenance

,quantity,symbol,value/equation,unit,temperature,phase/polytype,definition,source
0,Band gap,Eg,NaN,eV,TODO,TODO,direct/indirect,TODO
1,Electron mass,"Mc or mc,d",NaN,m0,TODO,TODO,curvature/DOS,TODO
2,Hole mass,"Mv or mv,d",NaN,m0,TODO,TODO,HH/LH/DOS,TODO
3,Valley degeneracy,gv,NaN,1,TODO,TODO,included in mass?,TODO
4,Conduction effective DOS,Nc,NaN,cm^-3,TODO,TODO,measured/derived,TODO
5,Valence effective DOS,Nv,NaN,cm^-3,TODO,TODO,measured/derived,TODO
6,Intrinsic concentration,ni,NaN,cm^-3,TODO,TODO,method,TODO

## 3. Published band-diagram interpretation

Attach or cite the permitted figure/data and identify:

- $E_V$ and $E_C$;
- direct or indirect gap;
- extrema locations and multiplicities;
- nearby thermally relevant bands;
- anisotropy and nonparabolicity evidence;
- whether a high-symmetry path could miss the actual extremum.

If digitizing a figure, save points to `data/digitized-band-data.csv` and record reciprocal-coordinate conversion and uncertainty.

In [3]:
band_evidence = pd.DataFrame([
    ("figure/data citation", "TODO"),
    ("reciprocal-space convention", "TODO"),
    ("conduction minimum and multiplicity", "TODO"),
    ("valence maximum and relevant bands", "TODO"),
    ("anisotropy/nonparabolicity", "TODO"),
    ("limitations of plotted path", "TODO"),
], columns=["evidence item", "finding"])
band_evidence

                         evidence item finding
0                 figure/data citation    TODO
1          reciprocal-space convention    TODO
2  conduction minimum and multiplicity    TODO
3   valence maximum and relevant bands    TODO
4           anisotropy/nonparabolicity    TODO
5          limitations of plotted path    TODO

## 4. Material parameter model

Implement $E_g(T)$ and construct all conduction and valence components using `src/semiconductor_model.py`. Do not mix phases, temperatures, or mass definitions without an explicit comparison.

In [4]:
material_configuration = {
    "material": None,  # TODO
    "phase_or_polytype": None,  # TODO
    "temperature_range_K": None,  # TODO
    "gap_model": None,  # TODO
    "conduction_components": [],  # TODO
    "valence_components": [],  # TODO
    "surface_states_included": False,
    "transport_included": False,
}
material_configuration

{'material': None,
 'phase_or_polytype': None,
 'temperature_range_K': None,
 'gap_model': None,
 'conduction_components': [],
 'valence_components': [],
 'surface_states_included': False,
 'transport_included': False}

## 5. Intrinsic temperature sweep

Calculate $N_C(T)$, $N_V(T)$, DOS curves, $\mu_i(T)$, $n(T)$, $p(T)$, and $n_i(T)$. Verify $n=p$ at every reported temperature and retain neutrality residuals.

In [5]:
intrinsic_result_schema = pd.DataFrame(columns=[
    "T (K)", "Eg (eV)", "Nc (cm^-3)", "Nv (cm^-3)", "mu_i (eV)",
    "n (cm^-3)", "p (cm^-3)", "relative neutrality residual",
])
intrinsic_result_schema

Empty DataFrame
Columns: [T (K), Eg (eV), Nc (cm^-3), Nv (cm^-3), mu_i (eV), n (cm^-3), p (cm^-3), relative neutrality residual]
Index: []

## 6. Published comparison

Compare at least one calculated $N_C$, $N_V$, $\mu_i$, or $n_i$ value/curve with literature. Report signed and percentage differences when meaningful and trace discrepancies to definitions rather than tuning parameters.

In [6]:
published_comparison = pd.DataFrame(columns=[
    "quantity", "temperature (K)", "calculated", "published", "unit",
    "signed difference", "percent difference", "source", "interpretation",
])
published_comparison

Empty DataFrame
Columns: [quantity, temperature (K), calculated, published, unit, signed difference, percent difference, source, interpretation]
Index: []

## 7. Sensitivity and uncertainty

At minimum vary $E_g$, electron DOS mass, and hole DOS mass within literature ranges. Show effects on both $n_i$ and $\mu_i$; distinguish parameter uncertainty from numerical error.

In [7]:
sensitivity_plan = pd.DataFrame([
    ("Eg", "TODO literature range", "ni and mu_i"),
    ("electron DOS mass", "TODO literature range", "ni and mu_i"),
    ("hole DOS mass", "TODO literature range", "ni and mu_i"),
], columns=["parameter", "variation", "reported response"])
sensitivity_plan

           parameter              variation reported response
0                 Eg  TODO literature range       ni and mu_i
1  electron DOS mass  TODO literature range       ni and mu_i
2      hole DOS mass  TODO literature range       ni and mu_i

## 8. Part III conclusion — TODO

Bound the intrinsic model's valid temperature and energy range. Discuss gap model, mass definition, degeneracy, nonparabolicity, additional bands, digitization uncertainty, statistics, and experimental nonstoichiometry/unintentional doping.